### ISSUE TITLE
Fix loading popups.

### ISSUE THREAD

**Issue by u17112592** [COS301-SE-2021/Document-Workflow#44]
Been testing on various branches but none of them seem to have working popups.

**Comment by u17112592** [comment]
The loaders do not function properly as loaders. They need to be dismissed according when the data we are waiting for comes through, not after a predetermined amount of time has passed.

**Comment by u17015741** [comment]
Completed the  loading components and they are in the workflow service. You can use the methods displayLoading() and dismissLoading() to call and dismiss it
