### ISSUE TITLE
Page not found page. 

### ISSUE THREAD

**Issue by u17112592** [COS301-SE-2021/Document-Workflow#73]
A page should be made for the sole purpose of alerting the user that they tried to navigate to a page that does not exist on the Document Workflow server. Think similar to what github does, since right now our sers are just met with a blannk screen. @u17015741 will need to adjust the routing for this.

**Comment by u17015741** [comment]
Have fixed the error in a way so that if a user goes to a random page , they will be redirected to the login page, is that satisfactory
