### ISSUE TITLE
Workflow Templates

### ISSUE THREAD

**Issue by u17112592** [COS301-SE-2021/Document-Workflow#92]

**Comment by u17112592** [comment]
Users should have the option to create a workflow based on a template that they have saved in the past. They should have the option to create these templates when creating a regular workflow. @u17015741 will need to implement the frontend functionality for this.

**Comment by u17015741** [comment]
Frontend has been made, need some help with pdftron @u17112592

**Comment by u17112592** [comment]
PDFTron has been implemented but @u17015741 I need you to replace the button ive added. The pdftron should only load in once everything else html-wise has loaded in for the Workflow creation.

**Comment by u17112592** [comment]
Everything necessary to implement this functionality has been implemented and tested.
